### ISSUE TITLE
Support hierarchical configuration & exclusive cfg files

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#4178]
I'm facing the problem in two services (MqttService and #4105 SSLService) that I'm in a need of a simple 2-level hierarchical configuration (parameters grouped in instance-able sections). I'm calling this "sections" in the followup text. I propose to add support to the framework in a way that GUIs can interact with sections (create/modify/delete) and that they can be stored in configuration files a human readable way.

## Comparison to ManagedService+ManagedServiceFactory

OSGi provides `ManagedServiceFactory` for similar use cases like this. Disadvantages:
* Ancient interface (Updates are published through `Dictionary`s)
* Also not supported by ESH at the moment:
   * REST/GUI can't delete instances nor create them
   * ConfigDispatcher can't handle the filename format "pid-subname.cfg" for a factory managed service.
   * The current solution doesn't support writing back to cfg files either
* We still need nested configurations (for example to configure a list of user credentials for a service)

## User interactions

The user would interact with sections as follows:
* A GUI (PaperUI) should be able to create a new section instance, edit an existing one and to remove an instance. Optional limits in the xml description prevent to many or to less instances.
* A cfg compatible file format can be used to express sections (INI sections, yaml indents).

### Example use cases (MqttService)
```
normal=config
other=value

[broker:connection1]
host=123.123.123.123
port=1234
secure=true

[broker:connection2]
....
```

The section type here is "broker" and two instances are configured. The instance name can alternatively be omited:
```
[broker]
host=123.123.123.123
port=1234
secure=true
```

A third alternative is to keep the key=value structure. Dots are used to separate key and instance name. Multiple levels are separated by hashes:
```
broker.connection1#host=123.123.123.123
broker.connection1#port=1234
broker.connection1#secure=true
```

This would be the flat representation of nested key,value structures for ConfigAdmin.

### Example use cases (SSLService)
```
algorithmConfig=secureAlgorithm

[context:default]
javaKeystore=default.keystore
keystorePassword=bfa7823ha7
privateKeyPassword=asdg23jh5a
automaticRefresh=true

[context:specialContext]
domain=www.mysmarthome.com
javaKeystore=external.keystore
keystorePassword=bfa7823ha7
privateKeyPassword=asdg23jh5a
useACME=true
```

### Other use cases
There are probably more use cases than only the two services that needs this. For instance I can think of user management related configuration where a section instance would consist of a username, a password, ssh key hash, etc.

## Implementation

I tried to visualize how I image this to work under the constraints that ConfigAdmin can only store flat key-values in the OSGi cache:

![esh-configadmin](https://user-images.githubusercontent.com/66436/30167185-ec57c244-9428-11e7-93d1-460c8b1848dc.png)

The next sections describe the components of the diagram.

### ConfigAdmin Plugin
* ConfigAdmin can only send flat <key,value> tuples.
* A [ConfigurationPlugin](https://felix.apache.org/apidocs/configadmin/1.2.4/org/osgi/service/cm/ConfigurationPlugin.html) can translate the flat map (see above, examples, option 3) to a nested map. Take the SSLService from above as an example. The section type "context" exists with two instances "default" and "specialContext". The value of key "context" should be a map with all instances of type `Map<String<Map<String,Object>>`.

An example of the entire configuration provided as Map<String,Object> to the service:
```
   algorithmConfig=secureAlgorithm
   context=
       default=
              javaKeystore=default.keystore
              keystorePassword=bfa7823ha7
              privateKeyPassword=asdg23jh5a
              automaticRefresh=true
       specialContext=
              domain=www.mysmarthome.com
              javaKeystore=external.keystore
```

### NestedConfigConverter
PR #4178

A helper class would need to be introduced to convert a nested/tree structure into a flat list of key-value tuples.

All services that
* use nested configuration
* are in a need to write back to ConfigAdmin,

would use this helper to convert their configuration to a flat one and then use ConfigAdmin to store it away.

### ConfigDispatcher: File storage

The file format might either stay like it is with a dotted/hash-character key-value format or is changed to a compatible INI or YAMP format. Sections are expressed with the [section] syntax or with indentations respectively.

### ConfigWriteBack: File storage
PR #4239

Some services would need to have changed or extended configuration written back to the according cfg file (or a new cfg file being generated if not existing). Those services should declare a special property in their DS, which also makes the cfg file an exclusive cfg file.

_Use-case_: The SSL Service generates a Private/Public-KeyPair on start and writes the passwords back to the configuration. Those passwords are necessary to obtain for the user to 1) backup the generated SSL configuration, 2) for the service to open the certificate file on next start.

A ConfigWriteBack service would observe the ConfigAdmin via [ConfigurationEvent](https://felix.apache.org/apidocs/configadmin/1.2.4/org/osgi/service/cm/ConfigurationEvent.html) and write changes of affected configurations back to the cfg file, in the same file format that ConfigDispatcher can read (might be a nested configuration).

This is similar to [Apache FileInstall](http://felix.apache.org/documentation/subprojects/apache-felix-file-install.html) `felix.fileinstall.enableConfigSave=true`, but the file format is more relaxed in ESH (due to `ConfigDispatcher`).

### Configuration.java
PR: #4181

The `Configuration` class provides unmarshalling to a POJO class. The as method would be extended to support nested structures and list of structures.

An example configuration class structure that benefits from nested unmarshalling and from list unmarshalling  (aka unmarshalling of sections):
```java
class ServiceConfiguration {
   BigDecimal importantNumber;
   String niceString;
   CoordinateConfiguration theCoordinates;
   List<UserConfiguration> users;
}

class CoordinateConfiguration {
   BigDecimal x;
   BigDecimal y;
}
class UserConfiguration {
   String username;
}
```

Some services (like the SSL Service) might want to write their configurations back to the ConfigAdmin. The Configuration class should be able to marshal values from a POJO class back to a Map.

### GUI: Introduce a new ConfigDescriptionSection
* Introduce a new ConfigDescriptionSection with:
  * A name, label, description
  * An optional minimum and maximum limit
  * A list of `ConfigDescriptionParameter`s.
* `ConfigDescriptionSection` would be added to `ConfigDescription`.
* A DTO need to exist

### GUI: Adapt the configuration dtd and parser
* Adapt the configuration dtd (http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd)
* `config.xml` package would need to be able to parse sections and add them to the `ConfigDescription` object.

A changed dtd could be:
```xml
<xs:complexType name="configDescription">
    <xs:sequence>
        <xs:element name="parameter-group" type="config-description:parameterGroup"
            minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="section" type="config-description:section"
            minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="parameter" type="config-description:parameter"
            minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    ...
</xs:complexType>
...
<xs:complexType name="section">
    <xs:all>
        <xs:element name="label" type="xs:string" minOccurs="0" />
        <xs:element name="description" type="xs:string" minOccurs="0" />
        <xs:element name="advanced" type="xs:boolean" minOccurs="0" />
        <xs:element name="parameter" type="config-description:parameter"
            minOccurs="0" maxOccurs="unbounded" />
    </xs:all>
    <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="min" type="xs:decimal" />
    <xs:attribute name="max" type="xs:decimal" />
</xs:complexType>
```

### GUI: REST interface and PaperUI
* The REST interface and PaperUI need to be adapted to transport config sections and present them

---

- [ ] Decide on cfg file format for nested configurations
- [x] NestedConfigConverter for Nested->Flat #4178
- [x] ConfigAdmin Plugin for Flat->Nested #4178
- [x] Configuration.java: Parse to nested objects and and marshal to nested maps #4181
- [x] Configuration Write-Back #4239
- [x] Configuration: Exclusive cfg files #4216
- [ ] GUI: REST interface and PaperUI

**Comment by triller-telekom** [comment]
Thank you for investing so much time to present an approach to enhance our configuration file structure.

You are mentioning in your points the places that need to be adjusted in order to make this work. Unfortunately you did not stress your last point "GUI: REST interface and PaperUI" enough. There is not just our PaperUI, but also 3rd party UIs like Habmin or other solutions that are based on ESH which have to be adjusted to deal with the new format. So this would be a huge API break.

Also another huge building block is the `ConfigDispatcher`. Currently it reads our `property style` configuration files. if we change that this is also a huge API break for solutions based on ESH.

How should we deal with these API breakings?

I am wondering what exactly the underlying problem is that you are trying to solve with the new configuration format. I can see that you are introducing nested sections, but as you described you could also achieve this in the flat configuration format using separators. There might even be another option to store your configurations, in the current `ConfigAdmin`.

I am sorry that you get this kind of feedback rather late while you have already started implementing things :(

**Comment by davidgraeff** [comment]
The solution is fully compatible to the current situation :) Thank you for the feedback, I'll go through your concerns:

> I am wondering what exactly the underlying problem is that you are trying to solve with the new configuration format.

At the moment it is not standardized, how multiple instances of something can be expressed in configuration files (and therefore also in the services that expect such configurations). MQTT transport was the first service (from the OH1 days) that came up with the dot syntax. The unfolding of the flat key-values to a hierarchical format is hand-written and not exposed. Every other service that needs this (the SSL service / the http ui addons service), they all need to reimplement this. So there need to be support for nested configuration in the core because it is used by multiple services.

> Currently it reads our property style configuration files. if we change that this is also a huge API break for solutions based on ESH.

Changing the config format is not necessary, but would be welcome. The ini style format is compatible to the java properties file (the sections would be read as keys without values). Only services that need nested configuration would benefit from sections in the file, in every other case it stays a normal properties file. So no API break here.

> You are mentioning in your points the places that need to be adjusted in order to make this work. Unfortunately you did not stress your last point "GUI: REST interface and PaperUI" enough. 

For all services that need nested configuration, the GUIs should sooner or later support this (via the REST interface). For all other services everything stays untouched. No API break here, but an API addition. Of course, I assume that we want to be able to configure everything via GUI at some point. If we do not attempt to ever configure MQTT or the SSL service via GUI, we do not need the REST interface additions. That's why I pretty much neglected it in the above summery.

**Comment by triller-telekom** [comment]
> MQTT transport was the first service (from the OH1 days) that came up with the dot syntax. The unfolding of the flat key-values to a hierarchical format is hand-written and not exposed. Every other service that needs this (the SSL service / the http ui addons service), they all need to reimplement this.

I see that it makes sense to implement it once for all services, but:

> For all services that need nested configuration, the GUIs should sooner or later support this (via the REST interface)

That is my point. if we introduce services that use the new configuration, we have to adjust ALL UIs so they are able to handle it.

> If we do not attempt to ever configure MQTT or the SSL service via GUI, we do not need the REST interface additions. 

We certainly DO want to configure them via GUI.

**Comment by sjka** [comment]
The key point is that the burden of supporting this kind of configuration is not only put onto _our_ REST API and PaperUI, but also on all solutions built on top of ESH - which are likely to bring their own UIs.

Therefore also the decision whether MQTT should be configured via GUI or not is not for us to make.

**Comment by davidgraeff** [comment]
The rest interface needs adaption, yes. I proposed the necessary changes but haven't made a pr. Guis do or do not support that rest feature. Habmin or other solutions are not required to support all rest interface features, would be nice do have this in paperui though. But are we at a point that we don't want a feature because GUIs would need adaption? :)

**Comment by davidgraeff** [comment]
@kaikreuzer Is this to be discussed at the conference or should this be decided on before? I have some PRs in the queue (all MQTT PRs starting with #4173), the SSLService PR #4105 and the LwM2M PR #4063, that would need more than flat key-values. And at least one other part of ESH (the service that adds addons to the index html) copied! the parser code of MQTT.

**Comment by htreu** [comment]
> But are we at a point that we don't want a feature because GUIs would need adaption?

Of cause not, I guess we all agree on the fact that we need nested configuration in some way or the other. Although for the framework we have to think of a solution which incorporates also the REST API and PaperUI.
The solution you are describing is a special case of a tree structure with only 3 levels of depth (broker -> property -> value). In case we do implement it like this its just a matter of time before we need the next level. And with handler configuration vs. device configuration in mind (see #3484) we will indeed need a more complex (read n-level depth) solution.
So imho we should discuss this further with a broader use case and also REST and PaperUI in mind.

**Comment by htreu** [comment]
Just to throw in a thought: Does the config admin to be aware of every single key/value pair of the configuration? Or is it sufficient to have a single key with a more complex structure encoded in YAML or JSON behind it?

**Comment by davidgraeff** [comment]
@htreu All PRs that I proposed here, are capable of multiple nested structures. The only thing that is restricted to a one level depth nesting structure is the proposed dtd.

**Comment by davidgraeff** [comment]
Is it possible to auto-generate the configDescription xml files by using custom annotations? Like with the OSGi DS xmls. This way the developer would fully describe the configuration of a service or binding in only one place.

**Comment by kaikreuzer** [comment]
>> But are we at a point that we don't want a feature because GUIs would need adaption?
> Of cause not, 

Hm, are you so sure? The issue really is that our config descriptions are a concept that is widely used in ESH. IF we add new features to it, we MUST make sure that all of this is nicely supported in all relevant places - and the main reason why config descriptions were introduced in the first place are the UIs. So yes, if we cannot adapt the GUIs accordingly, we must not add such a feature.
Note that it is like a can of worms: Once introduced, you cannot ever get rid of the complexity anymore. So if introducing such new stuff, we must be sure that it works out nicely, including the UIs.

I am not in all details of what is discussed here, but I mainly see to roads to move forward:
1. Design the services to require some specific more complex configurations and accept the fact that these are "technical" services that have to be configured through text - no config descriptions would be necessary here.
2. Break down the complexity of the configuration by splitting it into several configurations. When I read "broker -> property -> value", I would immediately assume that there should be instead one config for every broker, which then contains "property->value" entries only.

**Comment by davidgraeff** [comment]
I'm more familiar with other webkits than angular, but I can give it a try and provide a proof of concept pr for paperui as well.

rest interface changes would need to be discussed first though.

Configurations are used in two places. For services and for bindings/things. Services were my main target. It's unfortunate that the dtd is shared for both types. Because of that binding/thing config would need to be made fit for nested configuration as well I guess.

**Comment by kaikreuzer** [comment]
They are also used for Rule actions, templates, triggers, links, etc., and they will be used for any further new artifact that might be introduced in future. As I said, it is meant to be a general concept.

**Comment by htreu** [comment]
This is my attempt to recap the offline discussion we had about the nested configuration issue:

- we need at least a `section` based service configuration.
- this can be achieved using ManagedServiceFactory with different config files for every service instance.
- the exclusive `pid:my.servive.pid` marker could be extended by `pid:my.service.pid#context` to identify a single service.
- for example this could be used to configure several SSLContext services or several MQTT broker connections.
- ConfigDispatcher right now is capable of handling exclusive PID files and must be extended to "understand" the extra `#context` to configure a ManagedServiceFactory for the given `my.service.pid`.
- update/delete of these configurations is handled by the ConfigDispatcher as is.
- having PaperUI being extended to be able to create/modify/delete factory managed services is possible given the current ConfigDescription infrastructure and a hint in the service definition to be factory managed.

pleas add corrections & additions: @kaikreuzer, @sjka, @davidgraeff, @ViToni, @cweitkamp

**Comment by davidgraeff** [comment]
Sounds right. The last point is somehow more complicated though. Some instances might have been created by text files and shouldn't be editable by paperui anymore, isn't that right?

**Comment by htreu** [comment]
Right now PaperUI does not know about read only state of entities. For services the updated configuration is passed to the configAdmin (and propagated to the service instances) but changes are not reflected in the config files.

**Comment by triller-telekom** [comment]
FYI: I have created PR #4685 as @htreu proposed in https://github.com/eclipse/smarthome/issues/4178#issuecomment-339289002

**Comment by davidgraeff** [comment]
Nice work and a fruitful discussion. I close this now.
